version: "3.8"
services:
  es-proj:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: es_proj
    ports:
      - 35101:9200
    deploy:
      resources:
        limits:
          memory: 4GB
    environment:
      - ELASTIC_PASSWORD=admin
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - proj
    mem_limit: 34359738368
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
networks:
  proj:
    external: true
